/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface YoutubeListEmbedStencil {
    'height': string;
    'listid': string;
    'width': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLYoutubeListEmbedStencilElement extends Components.YoutubeListEmbedStencil, HTMLStencilElement {}
  var HTMLYoutubeListEmbedStencilElement: {
    prototype: HTMLYoutubeListEmbedStencilElement;
    new (): HTMLYoutubeListEmbedStencilElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'youtube-list-embed-stencil': HTMLYoutubeListEmbedStencilElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface YoutubeListEmbedStencil {
    'height'?: string;
    'listid'?: string;
    'width'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'youtube-list-embed-stencil': YoutubeListEmbedStencil;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'youtube-list-embed-stencil': LocalJSX.YoutubeListEmbedStencil & JSXBase.HTMLAttributes<HTMLYoutubeListEmbedStencilElement>;
    }
  }
}


